asiasite/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^accounts/', include('allauth.urls')),

    url(r'admin/', admin.site.urls),
    url(r'music/', include("music.urls")),
    url(r'apisection/', include("apisection.urls")),
    url(r'soundapi/', include("soundapi.urls")),

]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

music/urls.py
from django.conf.urls import url,include
from . import views
from django.contrib.auth.views import password_reset_done,login,logout,password_reset
app_name='music'
urlpatterns = [

    url(r'^$',views.IndexView.as_view(),name="index" ),
    url(r'^register/$', views.register, name='register'),
    url(r'^search/$', views.searchIndex, name='search'),
    url(r'^weather/$', views.weatherIndex, name='weather'),
    url(r'^profile/$', views.view_profile, name='profile'),

    url(r'^login/$', views.login_user, name='login'),
    url(r'^logout/$', views.logout_user, name='logout'),

    # music/<album_id>
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name="detail"),
    #music/album/2
    url(r'album/(?P<pk>[0-9]+)/$', views.UpdateAlbum.as_view(), name="album-update"),
#music/album/add
    url(r'album/add/$', views.CreateAlbum.as_view(), name="album-add"),
#music/album/2/delete
    url(r'album/(?P<pk>[0-9]+)/delete/$', views.DeleteAlbum.as_view(), name="album-delete"),
    url(r'^(?P<album_id>[0-9]+)/create_song/$', views.CreateAlbum.as_view(), name='create_song'),
    url(r'^songs/(?P<filter_by>[a-zA_Z]+)/$', views.CreateSong.as_view(), name='songs'),
    #music/myalbum
    url(r'^MyAlbum/$', views.AlbumView.as_view(), name='album'),

]

    # music/<album_id>/favoriet

music/models.py
from django.db import models
from django.urls import reverse#red pk 1
from django.contrib.auth.models import User
from django.db.models.signals import post_save

class Album(models.Model):
    user=models.ForeignKey( User,unique=False,on_delete=models.CASCADE,null=True)
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    gener = models.CharField(max_length=500)
    album_logo = models.FileField()
    def get_absolute_url(self):
        return reverse('music:detail',kwargs={'pk':self.pk})
    def __str__(self):
        return  self.album_title+'-'+self.artist
# Create your models here.
class Song(models.Model):
    album = models.ForeignKey(Album,on_delete=models.CASCADE)
    file_type = models.CharField(max_length=500)
    song_title = models.CharField(max_length=500)
    audio_file = models.FileField(default='',upload_to=u'mp3/', max_length=200)
    video_file = models.FileField(default='',upload_to=u'video/', max_length=200)

    is_favvioret=models.BooleanField(default=False)
    def __str__(self):
        return self.song_title
        return self.file_type

class Userprofile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    city=models.CharField(max_length=500)
    phone=models.IntegerField(default=0)
    def __str__(self):
        return self.user.username

def create_profile(sender,**kwargs):
    if kwargs['created']:
        user_profile=Userprofile.objects.create(user=kwargs['instance'])
    post_save.connect(create_profile,sender=User)

music/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import Album, Song

class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model=User
        fields=['username','email','password']

music/views.py
from django.views import generic
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth import authenticate,login,logout
from django.views.generic import View
from .forms import UserForm
from django.urls import reverse_lazy
from .models import Album,Song
import requests
from django.shortcuts import render_to_response



def view_profile(request):
    args={'user':request.user}
    return render(request,'music/profile.html',args)

class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'object_list'

    def get_queryset(self):
        return Album.objects.all()


class AlbumView(generic.ListView):
    template_name = 'music/album.html'
    context_object_name = 'object_list'

    def get_queryset(self):
        return Album.objects.filter(user=self.request.user)

class SongView(generic.ListView):
    template_name = 'music/songs.html'
    context_object_name = 'object_list'

    def get_queryset(self):
        return Song.objects.all()

class DetailView(generic.DetailView):
    model =Album
    template_name = 'music/detail.html'




class CreateAlbum(CreateView):
    model = Album

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(CreateAlbum, self).form_valid(form)
    fields = ['artist','album_title','gener','album_logo']

class CreateSong(CreateView):
    model = Song
    fields = ['album','file_type','song_title','audio_file','video_file']

class UpdateAlbum(UpdateView):
    model = Album
    fields = ['artist','album_title','gener','album_logo']


class DeleteAlbum(DeleteView):
    model = Album
    success_url= reverse_lazy('music:index')



def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                albums = Album.objects.filter(user=request.user)
                return render(request, 'music/index.html', {'albums': albums})
    context = {
        "form": form,
    }
    return render(request, 'music/registration_form.html', context)


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                albums = Album.objects.filter(user=request.user)
                return render(request, 'music/index.html', {'albums': albums})
            else:
                return render(request, 'music/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'music/login.html', {'error_message': 'Invalid login'})
    return render(request, 'music/login.html')
def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'music/login.html', context)
def searchIndex(request):
    template='music/searchapi.html'
    query=request.POST.get('q')
    urln = 'http://api.musixmatch.com/ws/1.1/track.search?apikey=1aa694f8617083fab82d3396a035c831&q_artist={}&page_size=3&page=1&s_track_rating=desc'

    req=requests.get(urln.format(query)).json()

    track_info = {
        'track_n' : req['message']['body']['track_list'][0]['track']['track_name'],
                       'album_name': req['message']['body']['track_list'][0]['track']['album_name'],
        'img': req['message']['body']['track_list'][0]['track']['album_coverart_100x100'],
                       'url': req['message']['body']['track_list'][0]['track']['track_share_url'],


    }


    context = {'track_info':track_info}
    a=render(request,'music/searchapi.html',context)
    return a


def weatherIndex(request):
    urln = 'http://api.openweathermap.org/data/2.5/weather?q=gaza&units=imperial&appid=2398c9d11bf92c38bac9f03d1054d924'

    r=requests.get(urln).json()

    city_weather = {
        'city': 'gaza',
       'temperature': r['main']['temp'],
       'description': r['weather'][0]['description'],
        'clear': r['weather'][0]['main'],

        'icon': r['weather'][0]['icon']
    }


    context = {'city_weather':city_weather}
    a=render(request,'music/weather.html',context)
    return a

music/templates/music/Song_form.html
{% extends 'music/base.html' %}
{% block body %}
    <br><br>
    <br><br>
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New Song</h3>
                <form class ="form-horizontal" action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% include 'music/form-template.html' %}
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button class="btn btn-success" type="submit">submit</button>

                        </div>
                    </div>

                </form>
            </div>

        </div>
    </div>


    </div></div>
{% endblock %}

music/templates/music/album.html
  <!--load path static css-->


{% extends 'music/base.html' %}
{% block body %}


    <div class="albums-container container-fluid">

    <!-- Albums -->
    <div class="row">
        <div class="col-sm-12">
            <h3>{{ user.username }}'s Albums</h3>
        </div>
{% if object_list %}


<ul>
    {% for album in object_list %}
        <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="{% url 'music:detail' album.id %}">
                            <img src="{{ album.album_logo.url}}" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h2>{{ album.album_title }}</h2>
                            <h4>{{ album.artist }}</h4></div>

    <li><a href="{% url 'music:detail' album.id %}">{{ album.album_title }}view detail</a></li>
        <form action="{% url 'music:album-delete' album.id%}" method="post" style="display: inline">

        {% csrf_token %}
        <input type="hidden" name="album_id" value="{{ album.id }}"/>
        <button type="submit" class="btn btn-default btn-sm"><span class="glyphicon glyphicon-trash"></span>

        </button>
        </form>
        <a href="#" class="btn btn-default btn-sm btn-favorite">
        <span class="glyphicon glyphicon-star"></span>
        </a></div></div></ul></div></div>
    {% endfor %}

{% else %}<h3>you dont have album yet</h3>
{% endif %}
{% endblock %}

music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block body %}
    <br><br>
    <br><br>
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New Album</h3>
                <form class ="form-horizontal" action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% include 'music/form-template.html' %}
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button class="btn btn-success" type="submit">submit</button>

                        </div>
                    </div>

                </form>
            </div>

        </div>
    </div>


    </div></div>
{% endblock %}

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}cloud music{% endblock %}</title>

{% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>


</head>
<body>
<nav class="navbar  navbar-header navbar-inverse navbar-fixed-top ">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapse" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <a class="navbar-brand" href="{% url 'music:index' %}">Cloudy</a>
      </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <
<! class="collapse navbar-collapse" id="collapse">
      <ul class="nav navbar-nav">

 <li>
     <a href="{% url 'music:album'%}">
                        <span class="glyphicon glyphicon-cd" aria-hidden="true">

                        </span>&nbsp; Album
     </a>
        <li/>
          <li>
     <a href="{% url 'music:songs' 'all'%}">
                        <span class="glyphicon glyphicon-music" aria-hidden="true">

                        </span>&nbsp;add_ Music
     </a>
        <li/>

      </ul>

          <form class="navbar-form navbar-left" role="search" method="post" action="{% url 'music:search' %} ">

              <div class="form-group">
                                          {% csrf_token %}

                  <input type="text" class="form-control" name="q" value="{{ request.Get.q }}">
              </div>
              <button type="submit" class="btn btn-defult">Serch</button>
          </form>


              <ul class="nav navbar-nav navbar-right">

                <li>
                    <a href="{% url 'music:album-add' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album
                    </a>
                </li>

                <li>
                    <a href="{% url 'music:weather' %}">
                        <span class="glyphicon glyphicon-cloud" aria-hidden="true"></span>&nbsp; My weather
                    </a>
                </li>


                  <li>
                <a href="{% url 'music:logout' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;logout
                    </a>
                  <li/>

              </ul>





    </div>



<!-- /.container-fluid -->
</nav>

{% block body %}

{% endblock %}
</body>
</html>

music/templates/music/create-song.html
{% extends 'music/base.html' %}
{% block title %}Add a New Song{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                        <a href="{% url 'music:detail' album.id %}">
                            {% if album.album_logo %}
                                <img src="{{ album.album_logo.url }}" class="img-responsive">
                            {% else %}
                                <h3>No image to display</h3>
                            {% endif %}
                        </a>
                    <h1>{{ album.album_title }} <small>{{ album.genre }}</small></h1>
                    <h2>{{ album.artist }}</h2>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation"><a href="{% url 'music:detail' album.id %}">View All</a></li>
                <li role="presentation" class="active"><a href="{% url 'music:create_song' album.id %}">Add New Song</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New Song</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="hidden" name="album" value="{{ album }}">
                        {% include 'music/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %}{{ album }}{% endblock %}

{% block body %}
<div class="container-fluid songs-container">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'music:detail' album.id %}">
                        {% if album.album_logo %}
                            <img src="{{ album.album_logo.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ album.album_title }} <small>{{ album.genre }}</small></h1>
                    <h2>{{ album.artist }}</h2>
                </div>
            </div>
        </div>

        <!-- proplem Song Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'music:detail' album.id %}">View All</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>All Songs</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Title</th>
                            <th>Audio File</th>
                        </tr>
                        </thead>
                        <tbody>
                        ///////
{%  for song in album.song_set.all  %}
                            <tr>
                                <td>{{song.song_title }}</td>
                                 <td>{{song.file_type }}</td>
                                 <td>{{song.is_favvioret }}</td>

                            </tr>
**{% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

music/templates/music/form-template.html
{% for filed in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ filed.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ filed.label_tag }}</label>
        <div class=" col-sm-10">
            {{ filed }}
        </div>
    </div>
{% endfor %}

music/templates/music/index.html
  <!--load path static css-->


{% extends 'music/base.html' %}
{% block body %}


    <div class="albums-container container-fluid">

    <!-- Albums -->
    <div class="row">
        <div class="col-sm-12">
            <h3>{{ user.username }}'s Albums</h3>
        </div>
{% if object_list %}


<ul>
    {% for album in object_list %}
        <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="{% url 'music:detail' album.id %}">
                            <img src="{{ album.album_logo.url}}" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h6>{{ album.user }}</h6>

                            <h2>{{ album.album_title }}</h2>
                            <h4>{{ album.artist }}</h4></div>

    <li><a href="{% url 'music:detail' album.id %}">{{ album.album_title }}view detail</a></li>
        <form action="{% url 'music:album-delete' album.id%}" method="post" style="display: inline">

        {% csrf_token %}
        <input type="hidden" name="album_id" value="{{ album.id }}"/>
        <button type="submit" class="btn btn-default btn-sm"><span class="glyphicon glyphicon-trash"></span>

        </button>
        </form>
        <a href="#" class="btn btn-default btn-sm btn-favorite">
        <span class="glyphicon glyphicon-star"></span>
        </a></div></div></ul></div></div>
    {% endfor %}

{% else %}<h3>you dont have album yet</h3>
{% endif %}
{% endblock %}

music/templates/music/login.html
{% extends 'music/base.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'music:login'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'music:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

music/templates/music/profile.html
{% extends 'music/base.html' %}
{%  block head %}<title>profile</title>
{% endblock %}
{% block body %}
    <br/><br/>

<div class="container">
    <h1>profile</h1>
<p>first name:{{ user.email }}</p>
<p>first name:{{ user.userprofile.city }}</p>
<p>last name:</p>
<p>email</p>
</div>

{% endblock%}

music/templates/music/registration_form.html
{% extends 'music/base.html' %}
{% block title %}register{% endblock %}

{% block body %}
    <br><br>
    <br><br>
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Create new account</h3>
                <form class ="form-horizontal" action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                        {% include 'music/form-template.html' %}
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button class="btn btn-success" type="submit">submit</button>

                        </div>
                    </div>

                </form>
            </div>

        </div>
    </div>


    </div></div>
{% endblock %}

music/templates/music/searchapi.html
{% extends 'music/base.html' %}
{% block body %}
    <section class="hero is-primary">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                </h1>
            </div>
        </div>
    </section>
    <section class="section">
        <div class="container">
            <div class="columns">
                <div class="column is-offset-4 is-4">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="field has-addons">
                            <div class="control is-expanded">
                                {{ form.name }}
                            </div>
                            <div class="control">

                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <section class="section">
<br/>
        <div class="container">
            <div class="columns">
                <div class="column col-md-6 is-6">
                    <div class="box" style="background-color: aliceblue">
                        <article class="media">
                            <div class="media-left">
                                <figure class="image is-50x50">
                                    <img src="{{ track_info.img }}" alt="Image">
                                </figure>
                            </div>
                            <div class="media-content">
                                <div class="content">
                                    <p>
                                        <span class="title">{{ track_info.track_n }}</span>
                                        <br>
                                        <span class="subtitle">{{ track_info.album_name }}</span>
                                        <br> <a href="{{ track_info.url }}">Track url</a>
                                    </p>
                                </div>
                            </div>
                        </article>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <footer class="footer">
    </footer>
</body>
{% endblock %}

music/templates/music/song.html
  <!--load path static css-->


{% extends 'music/base.html' %}
{% block body %}

<div class="container-fluid songs-container">

    <div class="row">
        <div class="col-sm-12">
            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" {% if filter_by == 'all' %}class="active"{% endif %}><a href="{% url 'music:songs' 'all' %}">View All</a></li>
                <li role="presentation" {% if filter_by == 'favorites' %}class="active"{% endif %}><a href="{% url 'music:songs' 'favorites' %}">Favorites</a></li>
            </ul>
        </div>
    </div>

    <div class="row">

        <div class="col-sm-12">

            <div class="panel panel-default">
                <div class="panel-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Song Title</th>
                                <th>Artist</th>
                                <th>Audio File</th>
                                <th>Album</th>
                                <th>Favorite</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for song in object_list %}
                                <tr>
                                    <td>{{ song.song_title }}</td>
                                    <td>{{ song.album.artist }}</td>
                                    <td>
                                        <a target="_blank" href="{{ song.audio_file.url }}">
                                            <button type="button" class="btn btn-success btn-xs">
                                                <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                            </button>
                                        </a>
                                    </td>
                                    <td>
                                        <a href="{% url 'music:detail' song.album.id %}">
                                            <img src="{{ song.album.album_logo.url }}" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;" />
                                        </a>
                                        <a href="{% url 'music:detail' song.album.id %}">{{ song.album.album_title }}</a>
                                    </td>
                                    <td>
                                        <a href="{% url 'music:favorite' song.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

music/templates/music/weather.html
{% extends 'music/base.html' %}
{% block body %}





    <div class="albums-container container-fluid ">


    <!-- Albums -->
    <div class="row">
        <div class="col-md-12  column is-offset-6 is-6">

            <h3>{{ city_weather.city }} Current weather</h3>
        </div>


<ul>
        <div class="col-sm-12 col-lg-2">
                    <div class="thumbnail">
                                    {{ city_weather.city }}

<img src="http://openweathermap.org/img/w/{{ city_weather.icon }}.png" alt="Image">
                        <div class="caption">
                                        <span class="subtitle">{{ city_weather.temperature }}° F</span>

                            <h4>{{ city_weather.description }}</h4>
                        </div>

        </div></div></ul></div></div>
{% endblock %}